[
  {
    "bookCode": "BK1",
    "libraryCode": "LID103",
    "title": "Ramayanam",
    "author": "Valmiki",
    "bookCategory": "Epic",
    "readTimeInHrs": 150,
    "rentalPrice": 50,
    "rating": 5.0,
    "bestSeller": "true",
    "available_books": 99,
    "rented_books": 1,
    "total_books": 100
  },
  {
    "bookCode": "BK3",
    "libraryCode": "LID105",
    "title": "Road to success",
    "author": "Chandu",
    "bookCategory": "Novel",
    "readTimeInHrs": 60,
    "rentalPrice": 30,
    "rating": 5.0,
    "bestSeller": "NO",
    "available_books": 10,
    "rented_books": 0,
    "total_books": 10
  },
  {
    "bookCode": "BK4",
    "libraryCode": "LID103",
    "title": "Githanjali",
    "author": "Rabindranath tagore",
    "bookCategory": "Novel",
    "readTimeInHrs": 45,
    "rentalPrice": 40,
    "rating": 4.3,
    "bestSeller": "NO",
    "available_books": 20,
    "rented_books": 0,
    "total_books": 20
  },
  {
    "bookCode": "BK5",
    "libraryCode": "LID105",
    "title": "Me Before You",
    "author": "Jojo Moyes",
    "bookCategory": "Love story",
    "readTimeInHrs": 30,
    "rentalPrice": 50,
    "rating": 4.5,
    "bestSeller": "NO",
    "available_books": 40,
    "rented_books": 0,
    "total_books": 40
  },
  {
    "bookCode": "BK6",
    "libraryCode": "LID105",
    "title": "Success",
    "author": "Chandra",
    "bookCategory": "Life",
    "readTimeInHrs": 2,
    "rentalPrice": 100,
    "rating": 4.5,
    "bestSeller": "NO",
    "available_books": 10,
    "rented_books": 0,
    "total_books": 10
  },
  {
    "bookCode": "BK7",
    "libraryCode": "LID105",
    "title": "Success",
    "author": "Chandra",
    "bookCategory": "Life",
    "readTimeInHrs": 2,
    "rentalPrice": 100,
    "rating": 4.5,
    "bestSeller": "NO",
    "available_books": 10,
    "rented_books": 0,
    "total_books": 10
  }
]
